version: '3'
name: currency-converter
services:
  api:
    build: .
    container_name: api
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - NODE_ENV=production
      - APP_PORT=${APP_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
  redis:
    image: redis:7
    container_name: redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
